matrix:
  include:
    #C with clang
    - os: linux
      language: c
      before_script:
        - wget https://download.savannah.gnu.org/releases/libgraph/libgraph-1.0.2.tar.gz
        - tar -xvf libgraph-1.0.2.tar.gz
        - pushd libgraph-1.0.2  && ./configure --prefix=/usr && make && sudo make install && popd
      script:
        make c
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libsdl1.2-dev
            - libsdl-image1.2 libsdl-image1.2-dev guile-1.8 guile-1.8-dev libsdl1.2debian libart-2.0-dev libaudiofile-dev libesd0-dev libdirectfb-dev libdirectfb-extra libfreetype6-dev libxext-dev x11proto-xext-dev libfreetype6 libaa1 libaa1-dev libslang2-dev libasound2 libasound2-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0"

before_install:
   - eval "${MATRIX_EVAL}"

