matrix:
  include:
    #C++ with g++
    - os: linux
      language: cpp
      script:
        ./scripts/build_cpp.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7"

before_install:
   - eval "${MATRIX_EVAL}"

